# Generated by Django 4.1.2 on 2022-10-13 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='failed_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 36, 47, 187812, tzinfo=datetime.timezone.utc), max_length=1500)),
                ('msg', models.CharField(max_length=1500)),
                ('receiver', models.CharField(max_length=1500, null=True)),
                ('if_sender', models.BooleanField(default=False)),
                ('if_rec', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dummsg',
            name='rec_msg',
        ),
        migrations.RemoveField(
            model_name='dummsg',
            name='sent_msg',
        ),
        migrations.AddField(
            model_name='dummsg',
            name='if_rec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dummsg',
            name='if_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dummsg',
            name='msg',
            field=models.CharField(default='lol', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dummsg',
            name='receiver',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='dummsg',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 36, 47, 184812, tzinfo=datetime.timezone.utc), max_length=1500),
        ),
    ]
