# Generated by Django 4.1.2 on 2022-10-13 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_failed_msg_remove_dummsg_rec_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 42, 51, 678451, tzinfo=datetime.timezone.utc), max_length=1500)),
                ('msg', models.CharField(max_length=1500)),
                ('receiver', models.CharField(max_length=1500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='failed_msg',
        ),
        migrations.RemoveField(
            model_name='dummsg',
            name='if_rec',
        ),
        migrations.RemoveField(
            model_name='dummsg',
            name='if_sender',
        ),
        migrations.AlterField(
            model_name='dummsg',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 42, 51, 676454, tzinfo=datetime.timezone.utc), max_length=1500),
        ),
    ]
