# Generated by Django 4.1.2 on 2022-10-13 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_failedmsg_delete_failed_msg_remove_dummsg_if_rec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedmsg',
            name='sender',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='dummsg',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 46, 39, 650515, tzinfo=datetime.timezone.utc), max_length=1500),
        ),
        migrations.AlterField(
            model_name='failedmsg',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 46, 39, 651514, tzinfo=datetime.timezone.utc), max_length=1500),
        ),
    ]
