# Generated by Django 4.1.2 on 2022-10-13 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_failedmsg_sender_alter_dummsg_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummsg',
            name='sender',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='dummsg',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 49, 15, 691605, tzinfo=datetime.timezone.utc), max_length=1500),
        ),
        migrations.AlterField(
            model_name='failedmsg',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 13, 11, 49, 15, 693587, tzinfo=datetime.timezone.utc), max_length=1500),
        ),
    ]
