# Generated by Django 4.1.2 on 2022-10-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dummsg_if_rec_dummsg_if_sender_alter_dummsg_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummsg',
            name='r_id',
        ),
        migrations.DeleteModel(
            name='FailedMsg',
        ),
        migrations.AddField(
            model_name='dumuser',
            name='messages_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dumuser',
            name='messages_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DumMsg',
        ),
    ]
